networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build:
      context: "./requirements/nginx"
    image: nginx:42
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/wordpress
    ports:
     - "443:443"
    networks:
      - inception
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PHP_HOST: ${PHP_HOST}
      PHP_PORT: ${PHP_PORT}
      WP_PATH: ${WP_PATH}
      CERTS_KEY: ${CERTS_KEY}
      CERTS_CRT: ${CERTS_CRT}
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: "./requirements/wordpress"
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      PHP_HOST: ${PHP_HOST}
      PHP_PORT: ${PHP_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WP_PATH: ${WP_PATH}
      WP_TITLE: ${WP_TITLE}
    secrets:
      - wp_user
      - wp_user_password
      - wp_user_email
      - wp_admin
      - wp_admin_password
      - wp_admin_email
      - db_user
      - db_user_password
      - db_root_password
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: "./requirements/mariadb"
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception 
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    secrets:
      - db_user
      - db_user_password
      - db_root_password
    restart: always

secrets:
  db_user:
    file: ../secrets/db_user
  db_user_password:
    file: ../secrets/db_user_password
  db_root_password:
    file: ../secrets/db_root_password
  wp_user:
    file: ../secrets/wp_user
  wp_user_password:
    file: ../secrets/wp_user_password
  wp_user_email:
    file: ../secrets/wp_user_email
  wp_admin:
    file: ../secrets/wp_admin
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_admin_email:
    file: ../secrets/wp_admin_email