networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build:
      context: "./requirements/nginx"
    image: nginx:42
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/wordpress
    ports:
     - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: "./requirements/wordpress"
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    secrets:
      - db_password
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: "./requirements/mariadb"
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

secrets:
  credentials:
    file: ./secrets/credentials.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt